### ISSUE TITLE
How to change Input type ? (ASCII /HEX )

### ISSUE THREAD

**Issue by mrpkarthik** [meetanthony/crcjava#1]
Hi, Please help me to change input type.

"**11010752533678900242700032010005**" - This is my input string..

it gives the following outputs :

**_ASCII :  CRC-16/X-25 | 0xAFCB
Hex : CRC-16/X-25 | 0x1279_**

above results got from web : http://crccalc.com/

But when i try the same using java library , it always giving "ASCII" Output only.
dont know where to change input type to HEX.

my code:

> String line = "11010752533678900242700032010005";
CrcCalculator calculator = new CrcCalculator(Crc16.Params[0]);
long result = calculator.Calc(line.getBytes(), 0, line.length());
            if (result != calculator.Parameters.Check) {
                System.out.println(calculator.Parameters.Name + " - BAD ALGO!!! " + Long.toHexString(result).toUpperCase());
            }

Note :  I have only one Param in Crc16 class. (Crc16X25) 

The above code returns "AFCB" but i need 1279(HEX output). 

Please help me on this..
Thanks

**Comment by meetanthony** [comment]
```
package com.crccalc;

public class Main {

    public static void main(String[] args) {
        String line = "11010752533678900242700032010005";
        CrcCalculator calculator = new CrcCalculator(Crc16.Crc16X25);
        
        byte[] bytes = hexStringToByteArray(line);

        long result = calculator.Calc(bytes, 0, bytes.length);
        if (result != calculator.Parameters.Check) {
            System.out.println(calculator.Parameters.Name + " - BAD ALGO!!! " + Long.toHexString(result).toUpperCase());
        }
    }

    public static byte[] hexStringToByteArray(String s) {
        int len = s.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(s.charAt(i), 16) << 4)
                    + Character.digit(s.charAt(i + 1), 16));
        }
        return data;
    }
}
```
Convert function from here:
https://stackoverflow.com/questions/140131/convert-a-string-representation-of-a-hex-dump-to-a-byte-array-using-java
