### ISSUE TITLE
How i can test The CRC-16/X-25 algorithm?

### ISSUE THREAD

**Issue by alfalfarias** [meetanthony/crcjava#2]
I have the next String of hex:
40402300043130303131313235323939383700000000000000C00701000000

And im trying to get the CRC-16/X-25 value what i know that is 0xA745 (i was tested it here: https://crccalc.com).

But i dont know how to recreate the case with this java code. Can you give me an example?

**Comment by meetanthony** [comment]
You can use the "Show processed data (HEX)" checkbox on the site to be sure which data has been processed by the algorithm on the site.
For your string, this is:
0x40 0x40 0x23 0x00 0x04 0x31 0x30 0x30  0x31 0x31 0x31 0x32 0x35 0x32 0x39 0x39
0x38 0x37 0x00 0x00 0x00 0x00 0x00 0x00  0x00 0xc0 0x07 0x01 0x00 0x00 0x00

Test code in java:
```
                byte[] test = new byte[]{
                        0x40, 0x40, 0x23, 0x00, 0x04, 0x31, 0x30, 0x30,
                        0x31, 0x31, 0x31, 0x32, 0x35, 0x32, 0x39, 0x39,
                        0x38, 0x37, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                        0x00, (byte)0xC0, 0x07, 0x01, 0x00, 0x00, 0x00};
                CrcCalculator calculator = new CrcCalculator(Crc16.Crc16X25);
                long result = calculator.Calc(test, 0, test.length);
                out.println(Long.toHexString(result).toUpperCase());
```

**Comment by alfalfarias** [comment]
@meetanthony , bro, very thanks. You are the first russian who help me, They others only ignores me, it works excellent. Very, very thanks.

**Comment by meetanthony** [comment]
You are welcome!
